### ISSUE TITLE
content assist after "Add" in Dialog

### ISSUE THREAD

**Issue by crapo** [GEGlobalResearch/DARPA-ASKE-TA1#107]
@kittaakos , if you have time, could you investigate why there is no content assist available in a Dialog window after the keyword "Add" (or "add")? Should be able to reproduce with any small ontology. The content should be classes and properties.

**Comment by kittaakos** [comment]
> why there is no content assist available

It's not implemented yet.

**Comment by crapo** [comment]
Is this a lot of effort to implement? I guess I don't understand how much CA is inherited from sadl and how much is unique implementation in Dialog.

**Comment by kittaakos** [comment]
> Is this a lot of effort to implement?

No, but I am still working on the rename/refactoring. (#104)

**Comment by crapo** [comment]
Great!! :-) I am very excited about that major improvement!

**Comment by kittaakos** [comment]
> The content should be classes and properties.

Did you mean SADL resources with either `OntConceptType.CLASS` or `OntConceptType.CLASS_PROPERTY` type? Can you please refine the requirements a bit? Thank you!

**Comment by crapo** [comment]
So the definition of the statement starting with "Add" is:
`NewExpressionStatement:
	('Add'|'add') 
	(newExpr=Expression
	)
;`
It isn't really that broad as it should probably be "real expressions", which in the SADL grammar start with ExpressionParameterized. In the shortterm, it would be very helpful if one could get a list of any SadlResource of type OntConceptType.CLASS, OntConceptType.CLASS_PROPERTY, or OntConceptType.RDF_PROPERTY. The latter two could have a range which is a class. But just the frist two would work for this week's objective.

**Comment by kittaakos** [comment]
I have implemented it. It's part of https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/pull/105.

![screencast 2020-04-22 10-43-30](https://user-images.githubusercontent.com/1405703/79961013-6698de80-8486-11ea-9fc3-b9a53517ae64.gif)
