### ISSUE TITLE
merge of MissingPatterns into GH-415

### ISSUE THREAD

**Issue by crapo** [GEGlobalResearch/DARPA-ASKE-TA1#117]
@kittaakos , now I really have problems. I merged MissingPatterns into GH-415 because I want to demo both renaming of concepts and the latest text extraction of code comments. Maven build failed in sadl.ui on something to do with something in src-xtend so I did a clean, then install. Now I have many errors in the eclipse environment. Can we do a Skype meeting? This is a major problem.

**Comment by kittaakos** [comment]
Sure. Please, send the invitation via mail.

**Comment by crapo** [comment]
@kittaakos , demo went well. Thank you for all your help!! The only glitch is that rename didn't work in the demo, and didn't work in the dry run earlier, although it worked repeatedly between. Unless it's an interaction with Zoom, there must be something I do in the demo that causes it. I'll search for a reproducible sequence. Thanks again!!!

**Comment by crapo** [comment]
One more thing. Now the demo is over we want to merge everything that you put into the demo branches into sadlos2 MissingPatterns and ASKE TA1 CodeExtraction. Please advise on best way to do that so that I don't corrupt my git repo again.

**Comment by kittaakos** [comment]
SADL PR: https://github.com/crapo/sadlos2/pull/417
Dialog PR: https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/pull/118

**Comment by crapo** [comment]
I think this is done.
