### ISSUE TITLE
Detecting and cleaning up when an editor window on a .dialog file is closed

### ISSUE THREAD

**Issue by crapo** [GEGlobalResearch/DARPA-ASKE-TA1#29]
@kittaakos , here is another loose end with which I could use some assistance. The AnswerCurationManager is persisted across invocations of the JenaBasedDialogModelProcessor. This is a necessity as it manages the answers to the questions, makes sure the same question isn't answered repeatedly, etc. However, when a Resource's editor window is closed, the AnswerCurationManger for the resource should either be discarded or cleaned. Right now the AnswerCurationManager is stored in the ConfigurationManager, of which there is one per resource, so that probably works as opposed to having a separate map of AnswerCurationManagaers keyed by Resource. So something needs to be a change listener that can do the cleanup.

**Comment by kittaakos** [comment]
Draft PR: https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/pull/31

**Comment by kittaakos** [comment]
Merged to the `master` via #31.
