### ISSUE TITLE
Incorrect color highlighting of instances from imported owl file.

### ISSUE THREAD

**Issue by agabaldon** [GEGlobalResearch/DARPA-ASKE-TA1#45]
Importing of on-the-fly created owl files into dialog is now working. The only issue remaining is that instances that are defined on those owl files appear color pink when used in answers from the CM. I'm attaching a project that reproduces the issue. Please open the file import.dialog, which already has the content to show the issue.
[ASKE_TA2.zip](https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/files/3735633/ASKE_TA2.zip)

**Comment by kittaakos** [comment]
Nice catch, @agabaldon. The highlighting code was broken in the SADL code-base. Here is the fix: https://github.com/crapo/sadlos2/pull/386

Can you please check out the [`external-highlight-fix`](https://github.com/crapo/sadlos2/tree/external-highlight-fix) branch in the SADL repository, and verify whether the highlighting issues are fixed.

Please close this item once the PR is good and merged to the `AugmentedTypes` branch. Thank you!

CC: @crapo
