### ISSUE TITLE
Dialog window CM addition display issue

### ISSUE THREAD

**Issue by crapo** [GEGlobalResearch/DARPA-ASKE-TA1#67]
@kittaakos ,  have a reproducible problem with the display of backend-inserted text in the Dialog window. Because of the services, it isn't easy for you to reproduce. Could we start by seeing if a collaborative debugging session sheds light on the issue before investing the time to get the services up and running for you? I'm available anytime today if you have a few minutes...

**Comment by kittaakos** [comment]
> Could we start by seeing if a collaborative debugging session sheds light on the issue before investing the time to get the services up and running for you? I

I would like to be able to reproduce it locally, if possible.

**Comment by crapo** [comment]
I think I found the problem with this. If it persists I'll have to figure out how to give you a working example.
