### ISSUE TITLE
performance investigations

### ISSUE THREAD

**Issue by kittaakos** [GEGlobalResearch/DARPA-ASKE-TA1#77]
@crapo, I am opening this thread to share my findings regarding the performance. It turned out very quickly, the bottle-neck is the `Turbo.sadl`, opening and touching (without saving) the file requires validation, the validation of this file takes ~7-8 seconds on my environment:
```
MacBook Pro (15-inch, 2016)
2.9 GHz Quad-Core Intel Core i7
16 GB 2133 MHz LPDDR3
```

I started to profile `Turbo.sadl`. I open the file wait for the validation, start profiler, touch the file by adding a single whitespace stop the profiler.

We spend most of the time at `com.ge.research.sadl.reasoner.utils.SadlUtils.classIsSubclassOf(OntClass, OntResource, boolean, List<OntResource>)`. See the attached HTML (inside the zip).

[Call-tree-–-All-threads-merged.html.zip](https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/files/4293620/Call-tree-.-All-threads-merged.html.zip)

I am going to play with this and try to figure out where can we speed it up.

**Comment by kittaakos** [comment]
Upstream PR: https://github.com/crapo/sadlos2/pull/405

**Comment by crapo** [comment]
Great job Akos!! This is refreshingly better!

**Comment by kittaakos** [comment]
> Great job Akos!! This is refreshingly better!

@crapo, if we want to further increase the performance numbers, we can still disable the "deep-validation" you have suggested last time. Let me know if you need it.

**Comment by crapo** [comment]
For the moment I think we're good. Let's see if we need further improvement before taking that complicating (for the user) step.
